DO
$$
BEGIN
    IF (
        SELECT NOT EXISTS(
            SELECT 1 FROM pg_extension WHERE extname = 'pg_tasks'
        )
    ) THEN
      CREATE SCHEMA IF NOT EXISTS tasks;
    END IF;
END
$$;

-- Template for user tasks.
-- Usage:
-- CREATE TABLE tasks.some_task(
--     LIKE tasks.template
--         INCLUDING DEFAULTS
--         INCLUDING IDENTITY
--         INCLUDING INDEXES,
--     some_useful_col text
-- );
CREATE TABLE tasks.template (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT now(),
    planned_to timestamptz DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    execution_count int DEFAULT 0,
    canceled bool,
    trace_id uuid,
    comment TEXT
);
CREATE INDEX tasks_created_at ON tasks.template(created_at);


-- Tasks registry.
-- Contains parameters for all tasks.
-- Function 'register_task()' creates entries automatically,
-- user MUST NOT edit or create entries!
CREATE TABLE tasks.types (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    schema_name text NOT NULL,
    table_name text NOT NULL,
    timeout interval DEFAULT NULL,
    notification_interval interval DEFAULT '1s',
    max_retries int DEFAULT 0,
    storage_time interval DEFAULT NULL
);


CREATE UNLOGGED TABLE tasks.last_notifications(
    task_type integer REFERENCES tasks.types PRIMARY KEY,
    last_notified_at time DEFAULT now()
);


CREATE FUNCTION tasks.create_stats_view() RETURNS VOID
LANGUAGE plpgsql AS $FUNC$
DECLARE
    tasks_num int;
    task RECORD;
    sql text = 'CREATE OR REPLACE VIEW tasks.stats AS ';
BEGIN
    SELECT COUNT(*) INTO STRICT tasks_num FROM tasks.types;

    IF tasks_num = 0 THEN
        sql = sql || 'SELECT NULL';
    ELSE
        FOR task IN SELECT
            types.schema_name,
            types.table_name
        FROM tasks.types
        LOOP
            tasks_num := tasks_num - 1;
            sql = sql || format(
                'SELECT %1$L AS table_name, * FROM tasks.stats_of_%1$I_%2$I',
                task.schema_name,
                task.table_name
            );
            IF tasks_num <> 0 THEN
                sql = sql || ' UNION ALL ';
            END IF;
        END LOOP;
    END IF;

    EXECUTE sql;
END;
$FUNC$;


CREATE OR REPLACE FUNCTION tasks.notify_workers() RETURNS TRIGGER
LANGUAGE plpgsql AS $FUNC$
BEGIN
    INSERT INTO tasks.last_notifications(task_type)
    SELECT id
        FROM tasks.types
        WHERE
            schema_name = TG_TABLE_SCHEMA AND
            table_name = TG_TABLE_NAME
    ON CONFLICT (task_type) DO UPDATE
        SET last_notified_at = now()
        WHERE (
            now()::time - tasks.last_notifications.last_notified_at
        ) > TG_ARGV[0]::interval;

    IF FOUND THEN
        PERFORM pg_notify('pg_tasks', TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME);
    END IF;

    RETURN NEW;
END;
$FUNC$;


CREATE FUNCTION tasks.register(
    schema_name text,
    table_name text,
    timeout interval DEFAULT NULL,
    max_retries int DEFAULT 0,
    notification_interval interval DEFAULT '1s',
    storage_time interval DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql AS $$
BEGIN

    -- Remove previous version of task objects, if exists
    PERFORM tasks.unregister(schema_name, table_name);

    -- Add entry with task parameters to tasks registry
    INSERT INTO tasks.types(
        schema_name, table_name, timeout,
        max_retries, storage_time
    ) VALUES (
        schema_name, table_name, timeout,
        max_retries, storage_time
    );

    -- Create trigger for notifications
    IF notification_interval IS NOT NULL THEN
        EXECUTE format(
            $QUERY$
                CREATE TRIGGER notify_on_new
                AFTER INSERT ON %1$I.%2$I
                FOR EACH STATEMENT
                EXECUTE FUNCTION tasks.notify_workers(%3$L);
            $QUERY$,
            schema_name,
            table_name,
            notification_interval
        );
    END IF;

    -- Create acquire func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION
            %1$I.%2$s(max_num int)
            RETURNS SETOF %3$s.%4$s
            LANGUAGE sql VOLATILE AS $FUNC$
                UPDATE %3$I.%4$I
                SET
                    execution_count = execution_count + 1,
                    started_at = now()
                FROM (
                    SELECT id
                    FROM %3$I.%4$I
                    WHERE
                        finished_at IS NULL AND
                        canceled IS NOT TRUE AND
                        execution_count <= %5$s AND
                        planned_to <= now() AND (
                            started_at IS NULL OR
                            now() - started_at > %6$L
                        )
                    ORDER BY created_at DESC
                    LIMIT max_num
                    FOR UPDATE SKIP LOCKED
                ) as acquired_tasks
                WHERE %3$I.%4$I.id = acquired_tasks.id
                RETURNING %3$I.%4$I.*
            $FUNC$;
        $QUERY$,
        'tasks',
        format('acquire_%s_%s', schema_name, table_name),
        schema_name,
        table_name,
        max_retries,
        timeout
    );

    -- Create finish func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION
            %1$I.%2$s(
                task_id int,
                started_at timestamptz,
                comment text DEFAULT NULL
            )
            RETURNS VOID
            LANGUAGE sql VOLATILE AS $FUNC$
                UPDATE %3$I.%4$I
                SET
                    finished_at = now(),
                    comment = %2$s.comment,
                    started_at = %2$s.started_at
                WHERE
                    finished_at IS NULL AND
                    canceled IS NOT TRUE AND
                    id = task_id;
            $FUNC$;
        $QUERY$,
        'tasks',
        format('finish_%s_%s', schema_name, table_name),
        schema_name,
        table_name
    );

    -- Create retry func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION
            %1$s.%2$s(
                task_id int,
                planned_to timestamptz DEFAULT NULL,
                comment text DEFAULT NULL
            ) RETURNS VOID
            LANGUAGE sql VOLATILE
            AS $FUNC$
                UPDATE %3$I.%4$I
                SET
                    started_at = NULL,
                    planned_to = %2$s.planned_to
                WHERE
                    finished_at IS NULL AND
                    canceled IS NOT TRUE AND
                    id = task_id;
            $FUNC$;
        $QUERY$,
        'tasks',
        format('retry_%s_%s', schema_name, table_name),
        schema_name,
        table_name
    );

    -- Create cancel func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION
            %1$s.%2$s(
                task_id int,
                planned_to timestamptz DEFAULT NULL,
                comment text DEFAULT NULL
            ) RETURNS VOID
            LANGUAGE sql VOLATILE
            AS $FUNC$
                UPDATE %3$I.%4$I
                SET
                    canceled = TRUE
                WHERE
                    finished_at IS NULL AND
                    id = task_id;
            $FUNC$;
        $QUERY$,
        'tasks',
        format('cancel_%s_%s', schema_name, table_name),
        schema_name,
        table_name
    );

    -- Create reset func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION %1$s.%2$s(task_id int)
            RETURNS VOID
            LANGUAGE sql VOLATILE AS $FUNC$
                UPDATE %3$I.%4$I
                SET
                    started_at = NULL,
                    finished_at = NULL,
                    execution_count = 0,
                    canceled = False
                WHERE id = task_id;
            $FUNC$;
        $QUERY$,
        'tasks',
        format('reset_%s_%s', schema_name, table_name),
        schema_name,
        table_name
    );

    -- Create clean func for task
    EXECUTE format(
        $QUERY$
            CREATE OR REPLACE FUNCTION %1$s.%2$s(
                finished_after interval DEFAULT %5$L
            ) RETURNS int
            LANGUAGE sql VOLATILE AS $FUNC$
                WITH deleted AS (
                    DELETE FROM %3$I.%4$I
                    WHERE now() - finished_at > finished_after
                    RETURNING id
                )
                    SELECT count(*) FROM deleted;
            $FUNC$;
        $QUERY$,
        'tasks',
        format('clean_%s_%s', schema_name, table_name),
        schema_name,
        table_name,
        storage_time
    );

    -- Create stats view for task
    EXECUTE format(
        $QUERY$
            CREATE VIEW %1$I.%2$I AS
            SELECT
                count(*) AS total,
                count(*) FILTER (WHERE planned_to_future) AS planned_to_future,
                count(*) FILTER (WHERE completed) AS completed,
                count(*) FILTER (WHERE completed AND retried) AS completed_with_retry,
                count(*) FILTER (WHERE completed_with_late) AS completed_with_late,
                count(*) FILTER (WHERE canceled) AS canceled,
                count(*) FILTER (WHERE not_started) AS not_started,
                count(*) FILTER (WHERE timeout) AS timeout,
                count(*) FILTER (WHERE outdated) AS outdated
            FROM (
                SELECT
                    id,
                    planned_to > now() AS planned_to_future,
                    finished_at IS NOT NULL AS completed,
                    canceled IS TRUE as canceled,
                    execution_count > 1 AS retried,
                    (
                        started_at IS NULL AND
                        planned_to > now()
                    ) AS not_started,
                    (
                        started_at IS NOT NULL AND
                        finished_at IS NULL AND
                        now() - started_at > %5$L
                    ) AS timeout,
                    (
                        started_at IS NOT NULL AND
                        finished_at IS NOT NULL AND
                        finished_at - started_at > %5$L
                    ) completed_with_late,
                    now() - created_at > %5$L AS outdated
                FROM %3$I.%4$I
            ) AS tasks;
        $QUERY$,
        'tasks',
        format('stats_of_%s_%s', schema_name, table_name),
        schema_name,
        table_name,
        timeout
    );

    -- Remove stats view for task
    DROP VIEW IF EXISTS tasks.stats;

    PERFORM tasks.create_stats_view();
END
$$;


CREATE FUNCTION tasks.unregister(
    schema_name text,
    table_name text
) RETURNS VOID
LANGUAGE plpgsql AS $$
DECLARE
    removed_entries int;
BEGIN
    -- Remove entry from tasks registry
    WITH deleted AS (
        DELETE FROM tasks.types WHERE
            types.schema_name = unregister.schema_name AND
            types.table_name = unregister.table_name
        RETURNING id
    )
    SELECT count(*) INTO STRICT removed_entries FROM deleted;

    IF removed_entries = 0 THEN
        RETURN;
    END IF;

    -- Remove acquire func for task
    EXECUTE format(
        'DROP FUNCTION tasks.acquire_%s_%s',
        schema_name, table_name
    );

    -- Remove finish func for task
    EXECUTE format(
        'DROP FUNCTION tasks.finish_%s_%s',
        schema_name, table_name
    );

    -- Remove retry func for task
    EXECUTE format(
        'DROP FUNCTION tasks.retry_%s_%s',
        schema_name, table_name
    );

    -- Remove cancel func for task
    EXECUTE format(
        'DROP FUNCTION tasks.cancel_%s_%s',
        schema_name, table_name
    );

    -- Remove reset func for task
    EXECUTE format(
        'DROP FUNCTION tasks.reset_%s_%s',
        schema_name, table_name
    );

    -- Remove clean func for task
    EXECUTE format(
        'DROP FUNCTION tasks.clean_%s_%s',
       schema_name, table_name
    );

    -- Remove stats view for task
    DROP VIEW IF EXISTS tasks.stats;

    -- Remove notifications trigger
    EXECUTE format(
        'DROP TRIGGER IF EXISTS %s.%s.notify_on_new',
       schema_name, table_name
    );

    -- Remove stats view for task
    EXECUTE format(
        'DROP VIEW tasks.stats_of_%s_%s',
        schema_name, table_name
    );

    -- Recreate generic stats view
    PERFORM tasks.create_stats_view();
END
$$;
